// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW2izI7HDQFQQS_dDlm5SIG9NPl3BcudU',
    appId: '1:775012978091:web:d8e3951e4d1bbc6a95d6ee',
    messagingSenderId: '775012978091',
    projectId: 'ethabah-f9a98',
    authDomain: 'ethabah-f9a98.firebaseapp.com',
    storageBucket: 'ethabah-f9a98.firebasestorage.app',
    measurementId: 'G-G4FYGBN65L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA77UXljNXNpY0Si0egm15Hsykge9gSHZs',
    appId: '1:775012978091:android:3aae6609e88301d695d6ee',
    messagingSenderId: '775012978091',
    projectId: 'ethabah-f9a98',
    storageBucket: 'ethabah-f9a98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-B26hLjcoVcQCWulSjnbqcKmnTYTNts',
    appId: '1:775012978091:ios:a92a5282a35ac91f95d6ee',
    messagingSenderId: '775012978091',
    projectId: 'ethabah-f9a98',
    storageBucket: 'ethabah-f9a98.firebasestorage.app',
    iosBundleId: 'com.example.ethabah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-B26hLjcoVcQCWulSjnbqcKmnTYTNts',
    appId: '1:775012978091:ios:a92a5282a35ac91f95d6ee',
    messagingSenderId: '775012978091',
    projectId: 'ethabah-f9a98',
    storageBucket: 'ethabah-f9a98.firebasestorage.app',
    iosBundleId: 'com.example.ethabah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW2izI7HDQFQQS_dDlm5SIG9NPl3BcudU',
    appId: '1:775012978091:web:53ca8611a709695495d6ee',
    messagingSenderId: '775012978091',
    projectId: 'ethabah-f9a98',
    authDomain: 'ethabah-f9a98.firebaseapp.com',
    storageBucket: 'ethabah-f9a98.firebasestorage.app',
    measurementId: 'G-TLFTMWL0NY',
  );
}
